version: '3'
services:
  db:
    image: mysql:8.0
    container_name: social_hub_mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./.db/mysql/data:/var/lib/mysql
      - ./.db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  redis:
    image: redis:6.0
    container_name: social_hub_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./.redis/data:/data
